---
name: ECS deploy workflow

on:
  create:
    tags:
      - "v*.*.*"

env:
  AWS_REGION: eu-central-1                    # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                              # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                              # containerDefinitions section of your task definition

jobs:
  metadata:
    name: Read metadata from file
    runs-on: ubuntu-latest
    outputs:
      platform: ${{ steps.meta.outputs.platform }}
      system: ${{ steps.meta.outputs.system }}
      subsystem: ${{ steps.meta.outputs.subsystem }}
      owner: ${{ steps.meta.outputs.owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read metadata
        id: meta
        uses: ./.github/actions/metadata-reader

      - name: test
        run: echo ${{ steps.meta.outputs.platform }}

  ecr:
    name: Create an ECR repository
    needs: metadata
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ needs.metadata.outputs.platform }} ${{ needs.metadata.outputs.system }} ${{ needs.metadata.outputs.subsystem }}
      - name: Deploy the cloudformation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "${{ needs.metadata.outputs.platform }}-${{ needs.metadata.outputs.system }}-${{ needs.metadata.outputs.subsystem }}-stack"
          template: ./.aws/ecr.yml
          parameter-overrides: "Name=${{ needs.metadata.outputs.platform }}/${{ needs.metadata.outputs.system }}-${{ needs.metadata.outputs.subsystem }}-repo"

  build:
    name: Build a docker image
    needs: ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta information
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            $ECR_REGISTRY/$ECR_REPOSITORY
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          #push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: my-container
          image: ${{ steps.build-image.outputs.image }}
